services:
  db:
    image: postgres:16
    container_name: airbnb_db
    environment:
      POSTGRES_USER: train
      POSTGRES_PASSWORD: Ankara06
      POSTGRES_DB: projectdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: airbnb_api
    env_file:
      - .env
    environment:
      DB_URL: postgresql://train:Ankara06@db:5432/projectdb
    volumes:
      # ðŸ”‘ MODEL ARTEFACT BURADA KALICI OLUR
      - ./backend/saved_models:/app/backend/saved_models
    ports:
      - "8502:8502"
    depends_on:
      - db

  ui:
    image: python:3.12-slim
    container_name: airbnb_ui
    working_dir: /app
    volumes:
      - ./frontend:/app
    env_file:
      - .env
    environment:
      API_URL: http://api:8502
    command: >
      bash -lc "pip install --no-cache-dir -r requirements.txt &&
                streamlit run streamlit_app.py --server.port 8501 --server.address 0.0.0.0"
    ports:
      - "8501:8501"
    depends_on:
      - api

volumes:
  pgdata:
