version: "3.8"

services:
  # =====================
  # POSTGRES
  # =====================
  db:
    image: postgres:16
    container_name: airbnb_db
    environment:
      POSTGRES_USER: train
      POSTGRES_PASSWORD: Ankara06
      POSTGRES_DB: projectdb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  # =====================
  # MINIO (MODEL STORE)
  # =====================
  minio:
    image: minio/minio:latest
    container_name: minio
    ports:
      - "9000:9000"   # S3 API
      - "9001:9001"   # Web Console
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  # =====================
  # FASTAPI API
  # =====================
  api:
    build:
      context: .
      dockerfile: backend/Dockerfile
    container_name: airbnb_api
    env_file:
      - .env
    environment:
      DB_URL: postgresql://train:Ankara06@db:5432/projectdb
      MINIO_ENDPOINT: minio:9000
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
      MINIO_BUCKET: ml-models
    ports:
      - "8502:8502"
    depends_on:
      - db
      - minio

  # =====================
  # STREAMLIT UI
  # =====================
  ui:
    image: python:3.12-slim
    container_name: airbnb_ui
    working_dir: /app
    volumes:
      - ./frontend:/app
    env_file:
      - .env
    environment:
      API_URL: http://api:8502
    command: >
      bash -lc "pip install --no-cache-dir -r requirements.txt &&
                streamlit run streamlit_app.py
                --server.port 8501
                --server.address 0.0.0.0"
    ports:
      - "8501:8501"
    depends_on:
      - api

volumes:
  pgdata:
  minio_data:
